version: '3.8'

services:
  web:
    build: .
    container_name: trustAgain_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

#   db:
#     image: postgres:13
#     container_name: django_db
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
