
services:
  web:
    build: .
    container_name: trustAgain_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: django_db
    env_file: # you are loading from .env not environment.
        - .env # all this credential is been saved in my environment variables.

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


