# Generated by Django 5.1.5 on 2025-03-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftnarrative",
            name="bm_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("large", "large"),
                    ("medium", "medium"),
                    ("small", "small"),
                    ("extra_large", "extra_large"),
                    ("none", "none"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
