# Generated by Django 5.1.5 on 2025-02-02 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=255)),
                ("client_name", models.CharField(max_length=255)),
                ("service_start", models.TimeField()),
                ("service_end", models.TimeField()),
                ("date_clock_in", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High Risk", "High Risk"),
                            ("Critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("report_notes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_in", models.DateField()),
                ("time_in", models.TimeField()),
                ("date_clock_out", models.DateField(blank=True, null=True)),
                ("time_clock_out", models.TimeField(blank=True, null=True)),
                ("report_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
