# Generated by Django 5.1.5 on 2025-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0002_alter_shiftnarrative_bm_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftnarrative",
            name="Time_in",
            field=models.TimeField(blank=True, help_text="Format: HH:MM:SS", null=True),
        ),
        migrations.AlterField(
            model_name="shiftnarrative",
            name="Time_out",
            field=models.TimeField(blank=True, help_text="Format: HH:MM:SS", null=True),
        ),
    ]
