# Generated by Django 5.1.5 on 2025-02-08 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trustagain_App', '0003_incidentreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftnarrative',
            old_name='service_end',
            new_name='Time_in',
        ),
        migrations.RenameField(
            model_name='shiftnarrative',
            old_name='service_start',
            new_name='Time_out',
        ),
        migrations.RemoveField(
            model_name='shiftnarrative',
            name='date_clock_in',
        ),
        migrations.RemoveField(
            model_name='shiftnarrative',
            name='severity',
        ),
        migrations.AddField(
            model_name='shiftnarrative',
            name='date_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shiftnarrative',
            name='date_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
