# Generated by Django 5.1.5 on 2025-02-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trustagain_App', '0004_rename_service_end_shiftnarrative_time_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
