# Generated by Django 5.1.5 on 2025-02-10 01:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0005_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timesheet",
            old_name="date_clock_out",
            new_name="date_out",
        ),
        migrations.RenameField(
            model_name="timesheet",
            old_name="report_note",
            new_name="report_notes",
        ),
        migrations.RenameField(
            model_name="timesheet",
            old_name="time_clock_out",
            new_name="time_out",
        ),
        migrations.RemoveField(
            model_name="shiftnarrative",
            name="staff_name",
        ),
        migrations.AddField(
            model_name="shiftnarrative",
            name="description",
            field=models.TextField(
                default=datetime.datetime(
                    2025, 2, 10, 1, 27, 44, 660954, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shiftnarrative",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
