# Generated by Django 5.1.5 on 2025-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0006_rename_date_clock_out_timesheet_date_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftnarrative",
            name="behaviour",
            field=models.CharField(default=" enter client behaviour", max_length=255),
        ),
        migrations.AddField(
            model_name="shiftnarrative",
            name="bm_size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shiftnarrative",
            name="bm_times",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftnarrative",
            name="symptoms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urinary pain", "urinary pain"),
                    ("constipation", "constipation"),
                    ("diarrhea", "diarrhea"),
                    ("vomiting", "vomiting"),
                    ("nausea", "nausea"),
                    ("fever", "fever"),
                    ("headache", "headache"),
                    ("other", "other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
