# Generated by Django 5.1.5 on 2025-03-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Trustagain_App",
            "0007_shiftnarrative_behaviour_shiftnarrative_bm_size_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftnarrative",
            name="behaviour",
        ),
        migrations.AddField(
            model_name="shiftnarrative",
            name="behaviour_description",
            field=models.CharField(default=" enter client behaviour", max_length=255),
        ),
    ]
