# Generated by Django 5.1.5 on 2025-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0008_remove_shiftnarrative_behaviour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftnarrative",
            name="description",
        ),
        migrations.AlterField(
            model_name="shiftnarrative",
            name="behaviour_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="shiftnarrative",
            name="bm_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("large", "large"),
                    ("medium", "medium"),
                    ("small", "small"),
                    ("extral_large", "extral_large"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
