# Generated by Django 5.1.5 on 2025-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trustagain_App", "0010_alter_shiftnarrative_bm_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftnarrative",
            name="symptoms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urinary pain", "urinary pain"),
                    ("constipation", "constipation"),
                    ("diarrhea", "diarrhea"),
                    ("vomiting", "vomiting"),
                    ("nausea", "nausea"),
                    ("fever", "fever"),
                    ("headache", "headache"),
                    ("other", "other"),
                    ("none", "none"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
